"""empty message

Revision ID: 1ef96a7ba175
Revises: 1fd9cf687cfd
Create Date: 2014-05-27 22:09:12.140770

"""

# revision identifiers, used by Alembic.
revision = '1ef96a7ba175'
down_revision = '1fd9cf687cfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    ### end Alembic commands ###
